Issue #117: links_on_spatial_condition failing for large spatial area
arup-group/genet pull request #126
Opened 2022-07-06 16:56 UTC by ana-kop

2022-08-25 12:44 UTC, KasiaKoz requested changes
A lot of code duplication happening here, I don't think you need to change anything in https://github.com/arup-group/genet/blob/4fcc3d36a49f8b042e7987082802ee61f3c2fc34/genet/core.py#L632 

---
Now that we're not relying on these `intersects` and `within` methods, it would be cleaner and more general to  get rid of the if statements and open up the `predicate` param: https://geopandas.org/en/stable/docs/reference/api/geopandas.sindex.SpatialIndex.valid_query_predicates.html so the user can choose from the geopandas list of operations and our code would simplify to:
```python
def _find_ids_on_shapely_geometry(self, gdf, predicate, shapely_input):
    geojson_input_gdf = ...
    return list(gpd.sjoin(gdf, geojson_input_gdf, how='inner', predicate=predicate)['id'])
```

2022-08-25 12:44 UTC, KasiaKoz commented on genet/core.py
> -            return list(gdf[gdf.intersects(shapely_input)]['id'])
as far as I understand that's the only line you need to change, the rest of the code falls in place

2022-08-25 12:44 UTC, KasiaKoz commented on genet/core.py
>              return list(gdf[gdf.within(shapely_input)]['id'])
I assume this is at risk too and should be updated similarly to intersection?

2022-08-25 12:44 UTC, KasiaKoz commented on genet/core.py
> +            return list(gpd.sjoin(gdf, geojson_input_gdf, how='inner', op='intersects')['id'])
`op` is deprecated, `predicate` should be used instead: https://geopandas.org/en/stable/docs/reference/api/geopandas.sjoin.html

2025-12-02 10:19 UTC, mfitz commented
Closing as will not fix.

2025-12-02 10:19 UTC, closed without merging