Split (active) modal subgraphs
arup-group/genet pull request #153
Opened 2022-10-24 09:43 UTC by KasiaKoz

Adds script to split given, comma separated modes from the links on the network graph under `'modes'` attribute. You end up with a graph with many more links, the links with mentioned modes exists only with that mode, all other attributes are copied across (for the time being anyway, we might have to set/scale capacity/speed eventually).

Context: We use Hermes in MATSim, which results in slower vehicles, like bikes, blocking cars on links. Creating separate links for that mode is an initial solution to that problem.

Bonus: Noticed a lag with method that adds links. Because with this script we're adding links with the same from and to nodes, we need to generate a multi-index (links are stores in the graph in this format: `(from_node, to_node, multiindex)`). One line, which gives a closer initial guess for the multi-index speeds things up for larger graphs:

![Screenshot 2022-10-24 at 10 34 20](https://user-images.githubusercontent.com/36536946/197496392-07f36c0a-c96e-4d59-87fb-9eb340417adb.png)
(time in seconds)

2022-10-25 11:49 UTC, mfitz requested changes
Looks good. Might benefit from a little more of an explanation about what the script is for and what it does in the help screen.

2022-10-25 11:49 UTC, mfitz commented on scripts/separate_modes_in_network.py
> +    logging.info('Generating validation report')
I like the automatic validation of the network following the change 👍

2022-10-25 15:25 UTC, KasiaKoz commented
Improved script description

2022-10-26 10:17 UTC, fredshone approved these changes

2022-10-26 18:56 UTC, mfitz approved these changes

2022-10-27 07:40 UTC, merged