Fix references to stop names changing during snapping+routing
arup-group/genet pull request #225
Opened 2024-01-25 16:43 UTC by KasiaKoz

Fixes #224

2024-01-26 22:14 UTC, brynpickering commented
How about `pd.Series(variable.extract_values())`? that's [what we use in calliope](https://github.com/calliope-project/calliope/blob/aad664ff1202d298e3265cd8994ca5e9a57788e9/calliope/backend/pyomo/util.py#L141)

2024-01-29 13:50 UTC, mfitz requested changes
The fix looks good, but I think we can come up with names for the new function and its test that give a better description of the behaviour.

2024-01-29 13:50 UTC, mfitz commented on genet/max_stable_set.py
> +def process_model_result(result_list: List[str]):
I am not sure about the name of this function. Is it processing model results? From what I can see, it's transforming stop names. Or is it more generic than that? Can we come up with a more descriptive name?

2024-01-29 13:50 UTC, mfitz commented on tests/test_max_stable_set.py
> +def test_processing_model_results(case_name, model_output, expected):
Great to see a dedicated unit test for this 👍 

As with the function under test though, I am not sure about the name.  How would you describe what we expect this new function to do? The current test name doesn't give me any clue about the behaviour we're verifying here. Is there a way to work the expected behaviour into the test name in a `test_does_something_when_something` style?

2024-01-29 15:58 UTC, KasiaKoz commented
I pulled out the entire code block that processes the model for solution variables - I didn't want to do it initially, because I really didn't want to mock loads of objects, but it turned out to not be that bad at all (no need to even use mocker). I noticed there was a dedicated method to get the index of the variable, which is much cleaner than processing the string representation of the variable.
I hope the method and test names look a lot better now too - let me know what you think @mfitz !

2024-01-29 18:22 UTC, mfitz approved these changes
Looks good! 👍

2024-01-30 10:06 UTC, merged