Finish updating docstrings
arup-group/genet pull request #232
Opened 2024-03-12 10:07 UTC by brynpickering

Updated docstrings I missed in #229 and added type hints to methods if they have an associated docstring. Now everything will render nicely in the docs :)

2024-03-27 12:07 UTC, KasiaKoz requested changes
Looks good, there are just a couple of small things:
- I think the description of the spatial tree is a bit off right now
- multiprocessing description needs a little ironing in one place, it mentioned `combine` as somewhat optional which might give the wrong idea (i think you still need to pass a method, even if that method is an identity map)

I think I left some other comments but those will be mostly just passing thoughts

2024-03-28 15:07 UTC, brynpickering commented on genet/utils/spatial.py
> +        linestring (LineString): _description_
They are included when autogenerating docs using [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring)

2024-05-16 14:41 UTC, brynpickering commented
@KasiaKoz bump to avoid this going stale!

2024-05-20 14:20 UTC, KasiaKoz approved these changes
👍

2024-05-28 09:27 UTC, merged